### ISSUE TITLE
No syntax highlighting. 

### ISSUE THREAD

**Issue by partisanyc** [pragmagic/vscode-nim#10]
Hi. I installed the package through the Command Palette, but when restarting, there is no syntax highlighting taking effect on .nim files. I have version 0.4.9 installed on VS Code 0.10.2 running on Ubuntu 14.04. Files are recognized as plain text and Nim is not in the list of available languages. 

Any ideas? Thanks in advance.

**Comment by kosz78** [comment]
Could you please open `Help->Toggle Developer Tools` main menu and look at console log for any error messages.
BTW, the current version of VS Code is `0.10.11`, update to a new version can help also

**Comment by partisanyc** [comment]
You are correct on both counts. There were errors in Console indicating that version 0.10.8 is required. I apologize for that, but the README indicates that 0.10 would be sufficient. 

I will upgrade VS. Thank you for your help!
