### ISSUE TITLE
Shift-Enter:  Send-Selected-Lines-To-REPL

### ISSUE THREAD

**Issue by bevo009** [pragmagic/vscode-nim#113]
I'd love to be able to shift-enter `send-selected-lines-to-REPL`  like we can do in Python, Coconut, Julia, F# etc.

Yes I know both our 2 REPLs aren't correct yet, but they are quite convenient for learning Nim. Code Runner can display selected lines, but there's no persistence, and it only displays actual print statements, unlike the REPLs which evaluate and display variables and expression results.

At present the workaround is to rename the file extension to *.py, and the Python plugin lets you `shift-enter` send to the Nim REPL (just Ctrl-D out of the Python REPL and `inim` or `nim secret` back in, then it works fine.)

It'd be great if I could do this instead from a .nim file. Thanks!

**Comment by tim-st** [comment]
It seems (at least for windows) it requires `"..."` around the path to make it work if the nim binary path has some specific chars in it like a space.
Currently it seems the first call is `C:\Program Files\Nim\bin\nim.exe secret` which is executed in the terminal of vs code and results in an error similar to (translated) `command "C:\Program" not found`.
