### ISSUE TITLE
Code completion for imports

### ISSUE THREAD

**Issue by tim-st** [pragmagic/vscode-nim#116]
As shown [here](https://github.com/PMunch/nimlsp/issues/12) I've implemented code suggestion for imports from stdlib and nimble packages, it would be nice if this plugin could support this feature too. Maybe someone can translate the nim code to javascript/typescript (and critbits to some Trie structure) to get this working.

**Comment by kosz78** [comment]
Fixed in 6dc215f1e046343cda5b96324f76994e3963aef4

**Comment by tim-st** [comment]
Thanks for your work on this!
Unfortunately it doesn't work for me (windows), the repl doesn't work too, maybe some windows specific problems? I looked in the log but there was no info.
