### ISSUE TITLE
Annoying auto complete when pressing '='

### ISSUE THREAD

**Issue by akbcode** [pragmagic/vscode-nim#123]
Whenever I press '=', I get a popup with suggestions for `` `-=` ``, `` `/=` ``, etc.
This becomes a problem when writing a proc, since '=' is the last character and pressing return replaces it with `` `-=` ``.

![equals](https://user-images.githubusercontent.com/17464386/61991862-ba84ad00-b045-11e9-8fe7-ab3c52eb8b7e.gif)

I've noticed this happens when editing code in the middle of the file, and not so much when appending code.

I'm using Nim 0.20.2, vscode-nim 0.6.3 and VS Code 1.36

**Comment by akbcode** [comment]
Is this an issue with this extension or nimsuggest?

**Comment by kosz78** [comment]
I guess this should be fixed in nimsuggest because vscode plugin is thin client for nimssugest, but @onelivesleft contributes some workaround solution for vscode and it can be merged
