### ISSUE TITLE
Code Helper (Renderer) hangs at 100% cpu usage rendering escape sequence

### ISSUE THREAD

**Issue by niv** [pragmagic/vscode-nim#132]
1) Create test.nim with this content:

```var h = "\x08\x01\x10\xc5\x85\x9e\xf2\x05\x18\x25\x20\x5f\x2a\x90\x01\x96\x67\x7c\x63\xf0\x1f\x5a\xac\xe3\xd5\x32\x7b\x94\xb3\x78\x7d\xb8\xea\xbc\x1b\x6b\xa3\xe6\xc8\x82\x91\xbf\xaf\x3d\x96\xc8\x58\x4d\x10\xf3\x48\x60\x4b\xde\xc7\x6d\x59\x38\xc3\x0f\xa3\xa1\x99\xe7\xa8\x88\xcc\x03\x1a\x09\x68\xf3\xdc\x94\x0c\x34\xfe\x88\x0f\xed\x2f\x18\xc8\xbc\x31\xe7\xc3\x6e\xb3\x9d\x21\xdb\x4a\xfd\xb8\x9f\x8d\x34\x4f\x4c\x87\x65\x08\x9e\xf0\xfe\xe1\xa2\x22\xc0\xd5\xcc\x52\xc4\x8e\x9c\x76\x7f\xb7\x0a\xfd\xb9\xd6\x68\x0f\x02\xc6\x62\xca\x41\x2d\x55\xca\x88\x40\x62\x5e\xee\x2c\xec\x30\x42\x39\x45\x60\xb0\xe7\x81\xc4\xca\x84\x93\xee\x52\x1f\x4a\x5b\xe7\x54"```

2) Open latest VSCode with latest nim extension and navigate to render test.nim

3) Code Helper (Renderer) will hang and editor will not be interactive anymore, forcing an app restart.

Tested on MacOS Catalina, have not verified other platforms.

**Comment by akbcode** [comment]
This [commit](https://github.com/pragmagic/vscode-nim/pull/126) is responsible for this bug. I reverted to earlier version of nim.json and the problem disappears.

**Comment by kosz78** [comment]
I have reverted pr
