### ISSUE TITLE
Can you mint a release?

### ISSUE THREAD

**Issue by Benjamin-Lee** [pragmagic/vscode-nim#144]
I came to the repo to file an issue requesting customizable line lengths and noticed that the PR has been merged, just is waiting for a release.

**Comment by kosz78** [comment]
Sorry for delay it will be released a soon

**Comment by Yardanico** [comment]
@kosz78 sorry for pinging, but any possible ETA? :)

**Comment by kosz78** [comment]
I have published release now, sorry for delay
