### ISSUE TITLE
Cannot compile nimsuggest on VS Code on Windows

### ISSUE THREAD

**Issue by couven92** [pragmagic/vscode-nim#15]
For some reason the plugin decides to compile nimsuggest (even though it is in my PATH).
Appearently that compilation fails, and a warning shows up in Code...

Where is the console output (I cannot seem to find it)? I cannot see what is the problem...

Visual Studio Code Version 1.2.0

**Comment by kosz78** [comment]
Please open `Help->Toggle Developer Tools` and look at console log. It should display output of compilation

**Comment by couven92** [comment]
Thanks! It turned out that I had a config error in my nim config file that caused the wrong architecture-toolset of the Visual Studio C/C++ compiler to be used...
