### ISSUE TITLE
Nim not found in path (only in 0.6.5)

### ISSUE THREAD

**Issue by dawkot** [pragmagic/vscode-nim#153]
When saving a .nim file, a notification pops up saying that it couldn't find the nim binary file in path despite it being there.

Tested with Linux (Manjaro stable), Nim devel and stable.

**Comment by smiga287** [comment]
Me too. I'm also on Manjaro and using stable Nim.

**Comment by mrgaturus** [comment]
Workaroud: `ln -s ~/.nimble/bin ~/.local/bin`
