### ISSUE TITLE
[question] does vscode-nim plugin work in latest nimsuggest?

### ISSUE THREAD

**Issue by yuutayamada** [pragmagic/vscode-nim#20]
Hello, although I'm an Emacs user, I have few questions because vscode-nim uses EPC same as Emacs. Recently I made some tests for nimsuggest and it worked major-restructured branch, but it didn't in master branch. I heard from Araq via IRC that vscode-nim is working fine (didn't ask which branch)

So, does vscode-nim plugin work in latest nimsuggest and nim of devel branch?
if it's yes, does vscode-nim use EPC protocol?
the protocol like (must have parenthesis):
```
FFFFFF(call id sug/chk/def,etc. ("projectfile" line column "dirtyfile")

FFFFFF is hex digit numbers, which represent total message size without the numbers
```
I'm wondering if I made wrong tests and vscode-nim's implementation (if it's same, we can share same tests)

Thanks

EDIT: I added about FFFFFF and nim of devel branch

**Comment by kosz78** [comment]
vscode-nim uses local copy of nimsuggest, it use the latest version from devel branch, After nimsuggest will modified in devel branch I will test it with vscode-nim and update  it in vscode-nim respectively

**Comment by yuutayamada** [comment]
Thank you for your answer. Let's me know if you have a issue using nimsuggest's master branch.
