### ISSUE TITLE
Provide more details in symbols window.

### ISSUE THREAD

**Issue by haiodo** [pragmagic/vscode-nim#27]
Hi,

Right now symbols window show a field name and file name and if file contains similar fields it looks weird. Could we have some more information, like line number or type name of field?

<img width="766" alt="screen shot 2016-11-07 at 09 18 33" src="https://cloud.githubusercontent.com/assets/477235/20044475/dd8c71f8-a4cb-11e6-99e9-a97ebec8ee0a.png">

**Comment by kosz78** [comment]
Fixed in 0.5.13 version
