### ISSUE TITLE
won't run when I hit F5

### ISSUE THREAD

**Issue by teroz** [pragmagic/vscode-nim#29]
I have downloaded the latest VSCode installed the nim extention on Kali Linux filled in the user settings as suggested here. Nim is installed and so is nimsuggest all working fine in Aporia. and created a  simple nim file in the tmp dir. 
  When I hit F5 to run a tiny dialog appers saying I should "suggest the environment" with options like Node js and some VS code extention. How do I tell this thing am running a nim file. This should be easier - WTF

**Comment by teroz** [comment]
![screenshot from 2016-11-16 13-19-24](https://cloud.githubusercontent.com/assets/853846/20345664/e49e12f8-ac00-11e6-8bb5-a324325570b9.png)

**Comment by kosz78** [comment]
I have added run selected file command in the extension it can be invoke from file context menu in editor or by press `F6` key, `F5` key already used in vscode for launch debug session.
This functionality is available in 0.5.13 version

**Comment by teroz** [comment]
Works a treat thank you
