### ISSUE TITLE
Project support

### ISSUE THREAD

**Issue by xxlabaza** [pragmagic/vscode-nim#31]
Hi, guys

Thanks a lot for your VS Code Nim plugin, it is very useful for me.

Could I donate to you for supporting the project? Maybe you want to setup a project in bountysource?

**Comment by kosz78** [comment]
Thank You for attention, the plugin is mostly based on nimsuggest tool that is provided by Nim compiler, I guess it will be better to support the main Nim project https://salt.bountysource.com/teams/nim
