### ISSUE TITLE
Incorrect indentation after string literal

### ISSUE THREAD

**Issue by dom96** [pragmagic/vscode-nim#32]
Type the following in:

```nim
"foobar"
```

Place the cursor after the `"foobar"` line and press enter. The cursor should end up on the next line at column 0, but it instead ends up indented once at column 2.

**Comment by dom96** [comment]
This is still broken for me in the latest version.

**Comment by kosz78** [comment]
@dom96 the issues should be fixed in the latest release

**Comment by dom96** [comment]
Wonderful. Thanks :)
