### ISSUE TITLE
The `not` keyword

### ISSUE THREAD

**Issue by dom96** [pragmagic/vscode-nim#34]
It seems that VS code does not consider `not` to be a keyword.

```nim
if not false:
  echo(42)
```

It should be highlighted the same as the ``if``.

**Comment by RSDuck** [comment]
It does highlights `not`(https://github.com/pragmagic/vscode-nim/blob/master/syntaxes/nim.json#L152).

The problem is probably the theme you're using.

Evidence:
![grafik](https://cloud.githubusercontent.com/assets/9352526/22443585/b20ae490-e73f-11e6-83a4-07db2e5cc34f.png)

**Comment by dom96** [comment]
Pretty sure i'm using the default theme. I would still consider that a bug since most people are likely using the default.

**Comment by RSDuck** [comment]
My bad. Yes, indeed, the default themes don't highlight `not`, while all other themes I have installed do.
