### ISSUE TITLE
Suggestions are often not shown.

### ISSUE THREAD

**Issue by yay** [pragmagic/vscode-nim#38]
Some suggestions are shown, but many are missing.

For example:

```nim
import htmlparser
import xmltree

let html = loadHTML("input.html")
let hrefs = html.   # `findAll` method is not in the suggestions when one hits the dot key
```

I've tried with the latest tip of `devel` and also `0.16.0` tag, Nim plugin v0.5.18. VS Code 1.9.1.

**Comment by RSDuck** [comment]
This was a known issue(https://github.com/nim-lang/nimsuggest/issues/44), but it is fixed in latest devel(I just tried it out, it suggests the findAll method). 

Are you sure you pulled the latest devel and compiled both the compiler and the tools?

**Comment by yay** [comment]
Well, let's find out, I did this:

```bash
git checkout devel
git pull
cd csources && sh build.sh
cd ..
bin/nim c koch
./koch boot -d:release
```

**Comment by endragor** [comment]
@yay you should also run `./koch tools -d:release` to build nimsuggest.
And building from csources is only needed for the first time. After pulling, if you already have `koch` and `nim` binaries, it's enough to just run:
```
./koch boot -d:release
./koch tools -d:release
``` 

@kos I think we should mention how to build nimsuggest in the README.

**Comment by yay** [comment]
@endragor Thank you, that worked!
