### ISSUE TITLE
Can't get it to work under MacOSX

### ISSUE THREAD

**Issue by bluenote10** [pragmagic/vscode-nim#42]
I'm using this extension successfully under Linux, but when trying to run the same setup under MacOSX, I can't get the linter/completion/go-to-definition features to work. I don't get any errors either, simply nothing happens in the moment where I expect these features. Features which don't need interaction with the compiler (like syntax highlighting) do work correctly.

Some details:

- `nim.lintOnSave` is set to `true`.
- `nim` and `nimsuggest` are symlinks within `~/bin`, which themselves link to binaries in `~/bin/nim-repo/bin/`. The `~/bin` directory is in my path (set within `.profile`). Running either `nim` or `nimsuggest` on the source files works from the command line. I'm using exactly the same approach in my working setup under Linux. Is it possible that under MacOSX the extensions has trouble locating `nim`/`nimsuggest`. Is it possible to find out if the extensions has located them correctly? I can't find any debug/log output, but I'm also new to VSC.

**Comment by kosz78** [comment]
Could you please look at Dev Tools Log:
![image](https://cloud.githubusercontent.com/assets/3992195/23642479/b2576b12-032d-11e7-91f3-b530b113401a.png)

**Comment by bluenote10** [comment]
I figured out what was causing the issue: I modified my path in `~/.profile` and apparently, in recent MacOSX versions, this affects only terminal sessions, but not applications launched from spotlight. I could solve the problem by modifying the path via `/etc/paths`, which seems to affect applications in general.
