### ISSUE TITLE
I can't install the plugin

### ISSUE THREAD

**Issue by krux02** [pragmagic/vscode-nim#47]
when I press install in visual studio code, the green button "install" becomes darker and says "installing". That is basically all that happens. No plugin installs. No error message, no log found in the console. It just doesn't do anything.

OS: arch-linux

Visual Studio Code:
```
Version 1.3.1
Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
Datum 2016-07-12T13:28:46.761Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

nim -version
```
Nim Compiler Version 0.16.1 (2017-03-22) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 097a96ec371f33d148396ed31a41e6575c61b2e1
active boot switches: -d:release
```

nimsuggest -version
```
Nim Compiler Version 0.16.1 (2017-02-19) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 5b5bd3811b5f6e7841128527cb098b23b373e7a6
active boot switches: -d:release --gc:markAndSweep
```

**Comment by endragor** [comment]
That seems to be VSCode's bug. See this: https://stackoverflow.com/questions/36234643/cannot-install-extensions-in-visual-studio-code (the author is also on Arch Linux and claims he eventually was able to install extensions).

They had this issue filed/fixed long ago, but seems it hasn't been completely fixed: https://github.com/Microsoft/vscode/issues/8859

**Comment by endragor** [comment]
Actually, your VSCode version is quite outdated. Have you tried the recent version? Try 1.10.x.

**Comment by krux02** [comment]
Well I forgot that visual studio code was an AUR package, I did the update now, and the problem is solved. Thank you for your support.
