### ISSUE TITLE
Folds shouldn't include the whitespace beneath the block

### ISSUE THREAD

**Issue by shmup** [pragmagic/vscode-nim#53]
Maybe this isn't what everyone is universally experiencing.

You can see that in my examples below, when folding a proc (or anything) it also wraps up all the whitespace beneath (even if it was many lines). In the case of folding everything, it creates a block of folds with no space in between.

![image](https://user-images.githubusercontent.com/118710/26849586-d76e1bde-4ad2-11e7-9fa5-a902af5537a5.png)

For an example, without folds then with the middle proc being folded:

<img width="106" alt="code_2017-06-06_16-07-22" src="https://user-images.githubusercontent.com/118710/26849539-9e4c5e1a-4ad2-11e7-95a7-dc8ec194642a.png">

<img width="112" alt="code_2017-06-06_16-07-32" src="https://user-images.githubusercontent.com/118710/26849545-a13ab432-4ad2-11e7-887b-d5936e1d4387.png">

**Comment by GULPF** [comment]
Is this finally solvable now?
https://github.com/Microsoft/vscode/issues/3353#issuecomment-330797736

**Comment by flamders** [comment]
Hmm, just got a new version with apt 1.17 and this seems fixed to me in python. Great work btw! Thank you, makes this editor much better.
