### ISSUE TITLE
Undeclared identifier: Channel

### ISSUE THREAD

**Issue by peheje** [pragmagic/vscode-nim#70]
I get undefined identifier on Channel and Thread etc. See image.
<img width="1440" alt="screenshot 2017-10-24 20 32 52" src="https://user-images.githubusercontent.com/7273366/31961578-62b5a9e6-b8fb-11e7-969a-e65845d5f269.png">

**Comment by peheje** [comment]
Solved: Create a file called nim.cfg in root, in it write --threads:on, restart VSCode, give it a few seconds.

**Comment by theAkito** [comment]
Works for the `threads` module, as well. That said, I honestly perceive this more like a workaround than an actual solution. Any chance this could be solved in the project, without requiring us to issue this workaround, @kosz78?

**Comment by RSDuck** [comment]
this isn't a workaround, nimsuggest has to learn which parameters you use from somewhere. Creating a nims/cfg file is recommended anyway so that the build parameters don't need to be given over command line every time.
