### ISSUE TITLE
in devel changed new line behavior results in not working linting

### ISSUE THREAD

**Issue by RSDuck** [pragmagic/vscode-nim#77]
Since https://github.com/nim-lang/Nim/commit/80caca15bd72e5dbc2712c1f0f6cbfa90262fbb2 `\n` results in a single line feed character and not in the platform specific new line character anymore. Therefore the `os.EOL` in https://github.com/pragmagic/vscode-nim/blob/124c8848a55fb73e2a2dc75bb842859b6752b96a/src/nimBuild.ts#L60 isn't splitting the(now by single line feeds seperated) text on Windows anymore, which breaks the linting using `nim check`.

For compability the best thing would probably be to split both by `os.EOL` and `\n` if `os.EOL != \n`. What do you think about this?

**Comment by kosz78** [comment]
Good suggestion, thank you

**Comment by kosz78** [comment]
Fixed by #78
