### ISSUE TITLE
Something wrong with syntax analyzing& Channels

### ISSUE THREAD

**Issue by r3d9u11** [pragmagic/vscode-nim#83]
Hi. I using type Channel and see that (also autocompletion doen't work; probably I must define something "--threads:on" for Nim's parser/autocompletion?):
![3](https://user-images.githubusercontent.com/15020827/37639533-d4674da2-2c22-11e8-8b68-e7a7918a7351.png)
But project compiles without errors and works fine.
What I'm doing wrong?
[thr_spawned_channels.zip](https://github.com/pragmagic/vscode-nim/files/1828180/thr_spawned_channels.zip)

**Comment by RSDuck** [comment]
create a file inside your `src` folder, named `nim.cfg` and put the following content inside it:
```
threads:on
```

You might also remove the `--threads:on` inside your `build_c_debug.nims` file

**Comment by r3d9u11** [comment]
@RSDuck thanks!

**Comment by oskca** [comment]
Adding `nim.cfg` works, but `vscode-nim` would ignore settings in `config.nims` which shall be of the same functionality of `nim.cfg` as [the documentation said](https://nim-lang.org/docs/nims.html)
