### ISSUE TITLE
nimsuggest "attacks" (one process per nim file in workspace)

### ISSUE THREAD

**Issue by oderwat** [pragmagic/vscode-nim#9]
Hi there. I have a folder which contains about 280 nim source files.. which leads to 280 nimsuggest processes when I use vscode. Is that really needed (a feature)?

**Comment by kosz78** [comment]
It is required run one instance Nimsuggest per nim project file. In case of non project mode, all workspace file are treated as project file for nimsuggest.
During IDE startup the extension index all workspace file for symbols that produce lot of processes, I will rewrite startup code to eliminate this behavior and also leave opened imsuggest only for opened nim file in IDE

**Comment by oderwat** [comment]
That would be good. Currently I have hundreds of nimsuggest still running even after ending vscode. I also found that suggestions stop working easily. But I would wait to analyze that until the "attack" gets fixed :)

**Comment by oderwat** [comment]
BTW.. I made this at the weekend.. https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow inspired by your work for Nim! I hope to optimize it (just recalculate when something is edited) when I get time.

**Comment by kosz78** [comment]
@oderwat very useful extension, thank you

**Comment by kosz78** [comment]
Fixed in 0.4.8 release
