### ISSUE TITLE
Improve Quick Info with reStructuredText

### ISSUE THREAD

**Issue by lmariscal** [pragmagic/vscode-nim#96]
Loving the extesion, just thought that since Nim docgen uses reStructuredText to parse the markup in the code comments it would be useful to have it in the quick info panel. 

Also the quick info panel doesn't show the documentation in ```var```, ```const``` or ```let``` types.

I would love to make a PR but have no experience making vscode extensions. Great work nonetheless 👍

**Comment by kosz78** [comment]
Documentation is provided by nimsuggest ide tools, and it dont provide documentation for `var`, `const` and `let`. I guess You need address Your request to https://github.com/nim-lang/nimsuggest project

I have added markdown support for completion documentation, it will be available in next release
