### ISSUE TITLE
Highlight # TODO

### ISSUE THREAD

**Issue by WilliamMauclet** [pragmagic/vscode-nim#97]
It would be nice for the TODO in a comment starting with "#[ ]TODO[...]"  to be in fat and illuminated in a certain colour. 

This is for example also done by the Python plugin.

Cheers!

**Comment by kosz78** [comment]
@WilliamMauclet [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) extension provide required functionality.
