### ISSUE TITLE
red squiggly lines on thread functions

### ISSUE THREAD

**Issue by peheje** [pragmagic/vscode-nim#98]
The extension keeps showing red squiggly lines under functions from the threads module. The code runs fine with --threads:on
![image](https://user-images.githubusercontent.com/7273366/46165660-7db72080-c291-11e8-9107-6aba93981f11.png)

**Comment by peheje** [comment]
Is there a way to disable the red squiggly lines? Or maybe tell the extension that threads are imported?

**Comment by RSDuck** [comment]
You already asked a question with the same solution a bit ago:
https://github.com/pragmagic/vscode-nim/issues/70

**Comment by peheje** [comment]
what a brainfart, sorry
